### PR TITLE
fix(post): parse error http request

### LINKED ISSUE #51: Bot suddenly crashing with SyntaxError
My bot suddenly crashes which happened after days of using it.
Error log:
```shell
SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Response.json (node:internal/deps/undici/undici:2279:23)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at Post.query (/app/node_modules/@devtomio/plugin-botlist/src/lib/Post.ts:197:71)
at BotList.postStats (/app/node_modules/@devtomio/plugin-botlist/src/lib/BotList.ts:38:4)
Node.js v18.6.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
```

### PR DESCRIPTION
**Pull request by kaname-png**
bump deps and fix #51

### CODE REVIEW

File: src/lib/Post.ts [hunk 1]
```diff
@@ -194,7 +194,13 @@ export class Post {
 
 			if (this.botList.options.debug) container.logger.debug(`[BotList-Plugin]: Posting to ${siteUrl} was successful.`);
 		} catch (err) {
-			if (err instanceof QueryError) this.botList.emit('postStatsError', await err.response.clone().json());
+			if (err instanceof QueryError) {
+				const error = err.response.clone();
+				let errorMessage = await error.json().catch(() => null);
+				if (!errorMessage) errorMessage = await error.text().catch(() => null);
```
Comment (vladfrangu) [inline src/lib/Post.ts:200]: This won't work as the body would be consumed already

**Review by vladfrangu — CHANGES_REQUESTED** [review]

File: src/lib/Post.ts (hunk 1 above)
Comment (kaname-png) [reply src/lib/Post.ts:200]: How should i put it?

File: src/lib/Post.ts [hunk 2]
```diff
@@ -194,7 +194,13 @@ export class Post {
...
+
+				this.botList.emit('postStatsError', errorMessage ?? 'Unknow error');
+			}
```
Comment (devtomio) [inline src/lib/Post.ts:203]:
```suggestion
			if (err instanceof QueryError) {
				const error = err.response.clone();
				let errorMessage = await error.text();

				try {
					errorMessage = JSON.parse(errorMessage);
				} catch {}

				this.botList.emit('postStatsError', errorMessage ?? 'Unknown error.');
			}
```
